### ISSUE TITLE
Improve route url

### ISSUE THREAD

**Issue by vegetabill** [lisaau/Booktonica#1]
It's a bit difficult to guess what this endpoint will return due to its names. Try using hierarchy in the name, e.g. `/parents/children` to make it a little more intuitive

https://github.com/lisaau/Booktonica/blob/3a160577a77f94a6431f54911eb349e2138c03ed/express-api/index.js#L50

**Comment by lisaau** [comment]
Improved route url for getting all books from a booklist.
