### ISSUE TITLE
[Refactor] DRY up books query

### ISSUE THREAD

**Issue by vegetabill** [lisaau/Booktonica#2]
Since you want the same columns in the `getBooksFromBooklist` and `getAllBooks` queries, maybe there is a way to have them both call a shared function or share this code so it's not duplicated

https://github.com/lisaau/Booktonica/blob/3a160577a77f94a6431f54911eb349e2138c03ed/express-api/src/booktonica-database.js#L60-L73

**Comment by lisaau** [comment]
Fixed in df6296
